### ISSUE TITLE
请转告陈华才根据larchintrin.h更新loongarch.h的函数名

### ISSUE THREAD

**Issue by redeastcn** [loongson/gcc#102]
抱歉，由于Linux分支不能提交Issues，所以就在这儿提交，请转告陈华才根据larchintrin.h更新loongarch.h的函数名。由于最新版的gcc更改了larchintrin.h文件的几处函数命名，而Linux的asm/loongarch.h还没及时更新，造成在用最新gcc编译内核的时候通不过。请通知陈更新一下，谢谢！另外，对你们的工作成果表示祝贺！

**Comment by yetist** [comment]
@chenhuacai 

你把 linux 的 issues 打开一下吧，然后 transfer issue 过去。

**Comment by xen0n** [comment]
这个分支编译出来也没用啊，固件不兼容，难道你是能拿到新固件的同学？

Meanwhile you could use [my branch](https://github.com/xen0n/linux/tree/loongarch-playground-xen0n-integration) which contains a fix.

**Comment by xry111** [comment]
> 这个分支编译出来也没用啊，固件不兼容

其实我本地有一份把物理地址相关修改一点一点改回去的代码 :)
