### ISSUE TITLE
consider using -mno-check-zero-division as the default?

### ISSUE THREAD

**Issue by xry111** [loongson/gcc#107]
@xen0n [wrote](https://reviews.llvm.org/D128572#3609897):

> Trapping division/modulus operations are signatures of MIPS codegen, and indeed here the trapping-by-default behavior and the flag seem to come from MIPS. However, as division-by-zero in LLVM IR is undefined behavior, why can't we just omit the trapping behavior altogether (and match RISCV in this regard), or at least disable the trapping by default?

RISCV gcc also [does not trap for zero divisor at all](https://godbolt.org/z/3revojsqz).

To me it makes sense to enable -mno-check-zero-division as the default, or at least the default for optimized code (with -O2 or more).

**Comment by xen0n** [comment]
Thanks for forwarding my comment here!

Indeed for the UB it's better to opt for the faster codegen. MIPS has trapping arithmetic, so it's probably okay for them to trap by default, but again it may be better to just ignore trapping everywhere, even on MIPS. We may not want to touch MIPS because it's changing a default behavior since long ago, but for LoongArch it's different.

**Comment by xry111** [comment]
Currently my intention is two submit two patches switching -mno-check-zero-division for default with -O1 or above.  But I'm not sure if "something" is still depending on SIGFPE to function...

**Comment by xen0n** [comment]
> Currently my intention is two submit two patches switching -mno-check-zero-division for default with -O1 or above, one for MIPS and one for LoongArch. But I'm not sure if "something" is still depending on SIGFPE to function...

That's why I don't want to touch MIPS, due to massive existing corpus of programs, but I think we can just flip for LoongArch. It's UB after all, and apparently awareness for this "feature" is very low, so I'd be hard-pressed to come up with a use case that implicitly depends on said behavior.

**Comment by xry111** [comment]
> > Currently my intention is two submit two patches switching -mno-check-zero-division for default with -O1 or above, one for MIPS and one for LoongArch. But I'm not sure if "something" is still depending on SIGFPE to function...
> 
> That's why I don't want to touch MIPS, due to massive existing corpus of programs, but I think we can just flip for LoongArch. It's UB after all, and apparently awareness for this "feature" is very low, so I'd be hard-pressed to come up with a use case that implicitly depends on said behavior.

Unfortunately I just seen this: https://github.com/sunhaiyong1978/CLFS-for-LoongArch/blob/main/CLFS_For_LoongArch64.md?plain=1#L1538

Not good...

**Comment by xen0n** [comment]
> > > Currently my intention is two submit two patches switching -mno-check-zero-division for default with -O1 or above, one for MIPS and one for LoongArch. But I'm not sure if "something" is still depending on SIGFPE to function...
> > 
> > 
> > That's why I don't want to touch MIPS, due to massive existing corpus of programs, but I think we can just flip for LoongArch. It's UB after all, and apparently awareness for this "feature" is very low, so I'd be hard-pressed to come up with a use case that implicitly depends on said behavior.
> 
> Unfortunately I just seen this: https://github.com/sunhaiyong1978/CLFS-for-LoongArch/blob/main/CLFS_For_LoongArch64.md?plain=1#L1538
> 
> Not good...

Relax; bash is one of the most portable programs ever written, and apparently it works fine on riscv, so it must contain logic for either flavor. ;-)

Check for `INTDIV0_RAISES_SIGFPE` in bash sources and you'll immediately realize it's perfectly okay for a division-by-zero to not SIGFPE. It's the CLFS doc that needs to be updated in this case...

**Comment by xry111** [comment]
> Relax; bash is one of the most portable programs ever written, and apparently it works fine on riscv, so it must contain logic for either flavor. ;-)
> 
> Check for `INTDIV0_RAISES_SIGFPE` in bash sources and you'll immediately realize it's perfectly okay for a division-by-zero to not SIGFPE. It's the CLFS doc that needs to be updated in this case...

Yes: if INTDIV0_RAISES_SIGFPE is used correctly, a program should not blow up somewhere x/0 does not trigger SIGFPE.

I'd like to perform a full system rebuild with -mno-check-zero-division in CFLAGS and see what will happen.  So I have to ask an off-topic question here: does your A2101 boot with new firmware with AMDGPU removed?  If it works I'll just use serial console. :)

**Comment by xen0n** [comment]
> So I have to ask an off-topic question here: does your A2101 boot with new firmware with AMDGPU removed? If it works I'll just use serial console. :)

I never plugged one yet, so the serial console definitely works.

`earlycon=uart,mmio,0x1fe001e0,115200n8 console=ttyS0,115200`

;-)

**Comment by xry111** [comment]
Done at https://gcc.gnu.org/r12-8546.
